version: "3.9"

services:
  # postgres setup
  postgres:
    container_name: mypg
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgresAdmin"
      POSTGRES_DB: "postgres"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3

  # pgadmin setup
  pgadmin:
    container_name: mypgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "calmantarasp@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pgAdmin"
      PGADMIN_LISTEN_PORT: 80
      # PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      # PGADMIN_CONFIG_LOGIN_BANNER: "Authorised users only!"
      # PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    # volumes:
    #   - ./pgadmin/private/var:/var
    #   - ./pgadmin/path/to:/certs
    #   - ./pgadmin/tmp:/pgadmin4
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  # redis setup
  redis:
    container_name: myredis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  # mongo setup
  mongo:
    container_name: mymongo
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "Admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    volumes:
      - ./mongo/data:/data/db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

  # mongo express setup debug only
  mongo-express:
    container_name: mymongoexpress
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "Admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "admin"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
