version: "3.9"

services:
  # elasticsearch
  es01:
    image: elasticsearch:7.13.2
    container_name: es01
    restart: always
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=elasticsearch,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/es01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      workenv_vnet:
        ipv4_address: 10.10.0.12

  es02:
    image: elasticsearch:7.13.2
    container_name: es02
    restart: always
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=elasticsearch,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/es02:/usr/share/elasticsearch/data
    networks:
      workenv_vnet:
        ipv4_address: 10.10.0.13

  es03:
    image: elasticsearch:7.13.2
    container_name: es03
    restart: always
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,elasticsearch
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/es03:/usr/share/elasticsearch/data
    networks:
      workenv_vnet:
        ipv4_address: 10.10.0.14

  kibana:
    image: kibana:7.13.2
    container_name: kibana
    hostname: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
      MONITORING_ENABLED: "true"
    networks:
      workenv_vnet:
        ipv4_address: 10.10.0.15

  logstash:
    image: logstash:7.13.2
    container_name: logstash
    hostname: logstash
    restart: always
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/settings/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      workenv_vnet:
        ipv4_address: 10.10.0.16

networks:
  workenv_vnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
