version: "3.9"

services:
  # elasticsearch
  elasticsearch:
    image: elasticsearch:7.5.1
    container_name: elasticsearch
    restart: always
    environment:
      # - node.name=es01
      - discovery.type=single-node
      # - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es01
      # - cluster.initial_master_nodes=es01
      # - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - default.path.logs=/var/log/elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/es01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      mcpiddev:
        ipv4_address: 10.0.0.12

  kibana:
    image: kibana:7.5.1
    container_name: kibana
    hostname: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      mcpiddev:
        ipv4_address: 10.0.0.15

  logstash:
    image: logstash:7.5.1
    container_name: logstash
    restart: always
    hostname: logstash
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/settings/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      mcpiddev:
        ipv4_address: 10.0.0.16

networks:
  mcpiddev:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1
