version: "3.9"

services:
  # elasticsearch
  elasticsearch:
    image: arm64v8/elasticsearch:7.13.2
    container_name: elasticsearch
    restart: always
    environment:
      # - node.name=es01
      - discovery.type=single-node
      # - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es01
      # - cluster.initial_master_nodes=es01
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - default.path.logs=/var/log/elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/es01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      workenv_vnet:
        ipv4_address: 10.10.0.12

  kibana:
    image: arm64v8/kibana:7.13.2
    container_name: kibana
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 8080:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      workenv_vnet:
        ipv4_address: 10.10.0.15

  logstash:
    image: arm64v8/logstash:7.13.2
    container_name: logstash
    restart: always
    hostname: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/settings/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      workenv_vnet:
        ipv4_address: 10.10.0.16

networks:
  workenv_vnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
