version: "3.9"

services:
  # postgres setup
  postgres:
    container_name: mypg
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgresAdmin"
      POSTGRES_DB: "postgres"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      workenv_vnet:
        ipv4_address: 10.10.0.2

  # pgadmin setup
  pgadmin:
    container_name: mypgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgAdmin"
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    # volumes:
    # - ./pgadmin/private/var:/var
    #   - ./pgadmin/path/to:/certs
    # - ./pgadmin/tmp:/pgadmin4
    networks:
      workenv_vnet:
        ipv4_address: 10.10.0.3

  # redis setup
  redis:
    container_name: myredis
    image: redis:latest
    command: redis-server --requirepass redisAdmin
    ports:
      - 6379:6379
    restart: always
    networks:
      workenv_vnet:
        ipv4_address: 10.10.0.4

  # mongo setup
  # mongo:
  #   container_name: mymongo
  #   image: mongo:latest
  #   ports:
  #     - 27017:27017
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: "Admin"
  #     MONGO_INITDB_ROOT_PASSWORD: "admin"
  #   volumes:
  #     - ./mongo/data:/data/db
  #   networks:
  #     vpcbr:
  #       ipv4_address: 10.10.0.6

  # mongo express setup debug only
  # mongo-express:
  #   container_name: mymongoexpress
  #   image: mongo-express:latest
  #   restart: always
  #   ports:
  #     - 9090:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: "Admin"
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: "admin"
  #   networks:
  #     vpcbr:
  #       ipv4_address: 10.10.0.7

networks:
  workenv_vnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
